#prod profile

spring: 
  datasource:    
      url:  jdbc:h2:file:./student_prod_db  
      username: prod-sa
      password:
      driverClassName:  org.h2.Driver
      
      
      
app:
  custom:
    property: http://prodhost:9090/service      


