#springbootrestprofiles demonstrates profiles example. Application run instantly no DB configuration required.

spring:
  application:
    name: springbootrestprofiles
  profiles:
    active: dev    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 8080  


#Enabling actuators  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        

#logging:
#  level:
#    org:
#      springframework:  DEBUG
     